### ISSUE TITLE
Reject/Decline Post

### ISSUE THREAD

**Issue by ibeandyy** [ezracr/vote-role-assignment#25]
UX Could be improved by implementing two new features:
1) Auto reject submission based off new parameter defined during thread/channel initiation, "Declined Vote Threshold"
2) Manual button to reject/decline submission by specific roles. Mostly used for when posts are being submitted that wildly miss the mark for PoW. 

The decline functionality should unpin the post, delete the bot's message

**Comment by ezracr** [comment]
> 1. Auto reject submission

You mean to add a timeout and after its expiration the message would be unpinned?

**Comment by ezracr** [comment]
- [ ] Auto reject submission based off new parameter defined during thread/channel initiation, "Declined Vote Threshold"
- [ ] Manual button to reject/decline submission by specific roles. Mostly used for when posts are being submitted that wildly miss the mark for PoW.
